# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
"""Video2SwimFish benchmark tasks.

Every registered id is ``Bench-<fish_tag>-<Kind>-v0`` and is generated per fish by
``scripts/benchmark/gen_fish_cfgs.py`` (which rewrites the block below the marker and
``salmon_benchmark_fish_cfgs.py``).  Kinds:

    TrajFollow-PCA        BLM + RL          (Task 1)
    TrajFollow-Joint      Joint RL / BCO+RL (Task 1; BCO+RL = this task + --checkpoint bc_policy.pt)
    TrajFollow-Joint-AMP  Joint RL + AMP    (Task 1)
    TrajFollow-CPG        CPG + RL          (Task 1)
    FreeSwim-VideoState   BLM+IL / BCO eval env (Task 2)
    ROVCatch              ROV basket capture (Case study)
    Calib                 skeleton-only kappa->joint calibration probe
    Reach10-PCA           BL-scaled reach-target task (kept for the ROV env's base class)
"""

import gymnasium as gym

from . import agents

# ---- BENCHMARK FISH (auto-generated by scripts/benchmark/gen_fish_cfgs.py) ----
gym.register(id="Bench-bluegill_fish015-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-bluegill_fish015-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish015PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-bluegill_fish020-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:BluegillFish020PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-catfish_fish001-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish001PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-catfish_fish002-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:CatfishFish002PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish001-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish001PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-lake_sturgeon_fish016-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:LakeSturgeonFish016PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadJointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadCPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadFreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadCalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadPCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadJointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish008_nohead-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish008NoheadPCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-TrajFollow-Joint-AMP-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointAMPTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020JointAMPTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-TrajFollow-CPG-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimCPGTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020CPGTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-FreeSwim-VideoState-v0", entry_point=f"{__name__}.salmon_swim_pca_videostate_env:SalmonSwimPCAVideoStateEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020FreeSwimVideoStateCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_pca_videostate_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-ROVCatch-v0", entry_point=f"{__name__}.salmon_rov_catch_bench_env:BenchROVCatchEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020ROVCatchCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_rov_chase_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-Calib-v0", entry_point=f"{__name__}.salmon_swim_env:SalmonSwimEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020CalibCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-TrajFollow-PCA-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimPCATrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020PCATrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_pca_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-TrajFollow-Joint-v0", entry_point=f"{__name__}.salmon_swim_traj_follow_env:SalmonSwimJointTrajFollowEnv", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020JointTrajFollowCfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_traj_follow_joint_cfg.yaml"})
gym.register(id="Bench-white_bass_fish020-Reach10-PCA-v0", entry_point=f"{__name__}.salmon_swim_reach10_env:SalmonSwimPCAReach10Env", disable_env_checker=True,
    kwargs={"env_cfg_entry_point": f"{__name__}.salmon_benchmark_fish_cfgs:WhiteBassFish020PCAReach10Cfg", "rl_games_cfg_entry_point": f"{agents.__name__}:rl_games_ppo_reach10_pca_cfg.yaml"})
